import React, { useEffect, useRef, useState } from "react";

import Head from "next/head";
import { useSupabaseClient } from "@supabase/auth-helpers-react";

import styles from "../pages/Home.module.css";


export default function Header({ showHeader = true }) {
  const supabaseClient = useSupabaseClient();

  return (
    <>
      <Head>
        <title>Avatar me</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.header}>
        <div>Avatar me!</div>
        {showHeader && <button
          style={{ marginTop: 0 }}
          className={styles.button}
          onClick={() => supabaseClient.auth.signOut()}
        >
          Logout
        </button>}
      </div>
    </>
  );
}
